name: Python application for System

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build: 
    runs-on: ShantanauLaptop-2

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print current Working directory
      run: echo "Current working directory:%CD%"
           cd C:\Windows\actions-runner\_work\_tool\Python\3.11.7\x64
       # $currentDirectory = Get - Location  

    - name: Download Python
      run: |
        cd C:\Windows\actions-runner\_work\_tool\Python\3.11.7\x64
        $downloadUrl = "https://github.com/actions/python-versions/releases/download/3.11.7-7098196908/python-3.11.7-win32-x64.zip"
        Invoke-WebRequest -Uri $downloadUrl -OutFile python.zip
        Expand-Archive -Path python.zip -DestinationPath python
        
    - name: Display Python extraction path
      run: |
        Set-Location -Path python
        Get-Location

    # - name: Add Python to PATH
    #   run: |
    #    echo "::add-path::${{ github.workspace }}/python"
    #    echo "PYTHON=${{ github.workspace }}/python/python.exe" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with the desired Python version
        cache: 'pip'
        architecture: 'x64'
        token: ${{ github.token }}
        cache-dependency-path: |
          ./path/to/dependency/file
      env:
        PYTHONUSERBASE: ${{ github.workspace }}/python
        CACHE_KEY: python-3.x-${{ runner.os }}
    
    - name: Python version
      run: python --version         
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
      
    - name: Run python script
      run: python Collection_Box.py
      working-directory: D:\a\Connectone_new\Connectone_new\Voucher_Entries
