name: Python application for System

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  run_python: 
    runs-on: DESKTOP-68EAEJ5

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Print current Working directory
      run: echo "Current working directory:%CD%"
      
       # $currentDirectory = Get - Location
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
      
    - name: Run python script
      run: python Collection_Box.py
      working-directory: D:\a\Connectone_new\Connectone\Voucher_Entries
    
