name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "main" ] 

jobs:
  run_python: 
    runs-on: [ShantanauLaptop-2]           

    steps:  
    
#    - name: Setup Browser
  # You may pin to the exact commit or the version.
  # uses: abhi1693/setup-browser@311d294ea9c5d710f61204ba3c4c3d31fa62443e
#      uses: abhi1693/setup-browser@v0.3.5
#      with:
    # The browser to install [chrome, edge, firefox].
#        browser: chrome
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print current Working directory
      run: echo "Current working directory:%CD%"
           cd C:\Windows\actions-runner\_work\Connectone_New
           echo "Current working after directory:%CD%"
      #shell: cmd
       # $currentDirectory = Get - Location

    - name: Python version
      run: python --version
         
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        venv\Scripts\activate
        pip install -r requirements.txt
        pip install webdriver-manager
      #working-directory: D:\a\Connectone_New\Connectone_New\requirements.txt

    - name: Install webdriver_manager
      run: |
        python -m pip install webdriver-manager selenium
      
    - name: Run python script
      run: python Bank_to_Bank_transfer.py
      working-directory: D:\a\Connectone_New\Connectone_New\Voucher_Entries
      #shell: cmd
