name: Python application for System

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build: 
    runs-on: ShantanauLaptop-2

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print current Working directory
      run: echo "Current working directory:%CD%"
           cd C:\Windows\actions-runner\_work\Connectone_New\Connectone_New
       # $currentDirectory = Get - Location  

    - name: Download Python
      run: |
        $downloadUrl = "https://github.com/actions/python-versions/releases/download/3.11.7-7098196908/python-3.11.7-win32-x64.zip"
        Invoke-WebRequest -Uri $downloadUrl -OutFile python.zip
        Expand-Archive -Path python.zip -DestinationPath python

    - name: Add Python to PATH
      run: |
        $pythonPath = "$(Agent.TempDirectory)\python"
        Write-Host "##[add-path]$pythonPath"
        Write-Host "##[set-env name=PYTHON]${pythonPath}\python.exe"

    - name: Python version
      run: python --version         
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
      
    - name: Run python script
      run: python Collection_Box.py
      working-directory: D:\a\Connectone_new\Connectone_new\Voucher_Entries
