name: Python application for System

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build: 
    runs-on: ShantanauLaptop-2

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print current Working directory
      run: echo "Current working directory:%CD%"
           $currentDirectory = Get - Location  
           #cd C:\Windows\actions-runner\_work\_tool\Python\3.11.7\x64

    # - name: Download Python
    #   run: |
    #     $downloadUrl = "https://github.com/actions/python-versions/releases/download/3.11.7-7098196908/python-3.11.7-win32-x64.zip"
    #     Invoke-WebRequest -Uri $downloadUrl -OutFile python.zip
    #     Expand-Archive -Path python.zip -DestinationPath python
        
    # - name: Display Python extraction path
    #   run: |
    #     Set-Location -Path python
    #     Get-Location

    # - name: Add Python to PATH
    #   run: |
    #    echo "::add-path::${{ github.workspace }}/python"
    #    echo "PYTHON=${{ github.workspace }}/python/python.exe" >> $GITHUB_ENV

    # - name: Set up Python
    #   run: |
    #     Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.9.7/python-3.9.7-amd64.exe" -OutFile python-3.9.7-amd64.exe
    #     # Install Python silently
    #     Start-Process python-3.9.7-amd64.exe -ArgumentList "/quiet", "InstallAllUsers=1", "PrependPath=1" -Wait

    # - name: Install Python
    #   run: |
    #      Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.9.6/python-3.9.6-amd64.exe -OutFile python-installer.exe
    #      Start-Process -Wait -FilePath python-installer.exe -ArgumentList "/quiet", "InstallAllUsers=0", "PrependPath=1", "Include_test=0", "Include_launcher=0", "TargetDir=C:\Python39"
    #      Remove-Item python-installer.exe

    - name: Add Allure to PATH
      run: |
         echo "C:\Users\Shantanu\scoop\apps\allure\2.24.0\bin" >> $GITHUB_PATH

    - name: Allure version
      run: C:\Users\Shantanu\scoop\apps\allure\2.24.0\bin\allure.bat --version

#note: in your _work folder python should there, and in system variable: python, pytest, pip path, and python/scripts
    - name: Python version
      run: python.exe --version         

    - name: pip version
      run: |
       python -m pip --version   
       python -m pip freeze 
      
  #  - name: Install dependencies
  #    run: python install -r requirements.txt
       # C:\Python\python.exe -m pip install --upgrade pip
 #       cd C:\Windows\actions-runner\_work\Connectone_New\Connectone_New
         
# for pytest, kept it in a script folder and environment variable
    - name: pytest version 
      run: python -m pytest --version
      # python -m pip install selenium
        
    - name: Run python script
      run: |
       pytest test_BanktoBank.py --alluredir=./allurereports
       C:\Users\Shantanu\scoop\apps\allure\2.24.0\bin\allure.bat serve ./allurereports
      working-directory: C:\Windows\actions-runner\_work\Connectone_New\Connectone_New\Test_Voucher
