name: Python application for System

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build: 
    runs-on: ShantanauLaptop-2

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print current Working directory
      run: echo "Current working directory:%CD%"
           cd C:\Windows\actions-runner\_work\Connectone_New\Connectone_New
       # $currentDirectory = Get - Location  

    - name: Set up Python 3.11
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.11
      env: 
        CACHE_KEY: python-3.11-${{ runner.os }}

    - name: Python version
      run: python --version         
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
      
    - name: Run python script
      run: python Collection_Box.py
      working-directory: D:\a\Connectone_new\Connectone_new\Voucher_Entries
